### PR TITLE
More detailed gas estimation

### PR DESCRIPTION
**Pull request by cuongquangnam**
#### What this PR does / why we need it:
- This is a more detailed estimation of gas based on EVM specification and EIP-1559. ( in file ./scripts/gasEstimation2.ts)
- The average estimation is 173 DFI (around 60 USD at price 1 DFI = 0.34 USD) , whether the worst-case estimation is 570 DFI (around 200 USD at price 1 DFI = 0.34 USD)
- A note that at the same price of 0.34 USD, the script gasEstimation gives an estimation of 35 USD per month
- The other way of using batchCallByBot to update the values prove to save a little bit of gas (average: 171 DFI, worst-case: 568 DFI). The reason seems to be the 21000 intrinsic gas cost for each transaction.

### CODE REVIEW

**Comment by Abhishekkochar** [comment]
Is there a reason why aren't we using Bot for this? We will primarily use the relayerBot instead of manual txs (gasEstimation2.ts). What would be better to see is if using `batchCallByBot()` instead of manually calling all functions, saves us any gas.

**Comment by cuongquangnam** [comment]
The point here is to give theoretical estimation to account for different situations based on Ethereum documentation. Therefore, I don't use the bot (otherwise, will have to create custom data for those situations to feed to the bot, which I doubt would make the result any different)
Sure, we can add the experiment with bathCallByBot() later.

**Comment by Abhishekkochar** [comment]
> The point here is to give theoretical estimation to account for different situations based on Ethereum documentation. Therefore, I don't use the bot (otherwise, will have to create custom data for those situations to feed to the bot, which I doubt would make the result any different) Sure, we can add the experiment with bathCallByBot() later.

I understand. But this won't effect us in one or another way. We most likely never going to process txs this way anyway except for admins. This is surely good to have. 

However, `gasEstimation.ts` script using the relayerBot, that cost 35 usd P/M where as a this one is 60(guessing this is monthly) usd P/M.

Can we also add the gasEstimation for `bathCallByBot` in this PR? It will be good to have the total estimate of gas when calling individual function vs batchCall.

**Comment by cuongquangnam** [comment]
Hmm, I don't see the difference between updating using the estimation script files and the bot file. (the only difference is the  numeric values to update to the storage). But as it turns out, the numeric values only matter when it comes to the SSTORE operations (as explained briefly through the .md file).

My guess for why in reality the gas cost is smaller is because there are some attributes where the new values are the same as the old value, and gas cost for such SSTORE operation is cheaper than normal ([reference](https://github.com/wolflo/evm-opcodes/blob/2b745ab5cbfac720967e87c2d545b2dbcec2856a/gas.md?plain=1#L196)).

Added the script for estimation of gas for batchCallByBot btw.

**Review by Abhishekkochar — CHANGES_REQUESTED** [review]
Over all looks good. Can you also add `COIN_MARKET_CAP_API` in .env.example.

**Review by Abhishekkochar — APPROVED** [review]
LGTM

**Pull request merged**
